apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../config/default

# This field is deprecated in Kustomize v5; however, we rely on an earlier version and cannot use `patches` yet.
patchesStrategicMerge:
- ./patches/aso-disable-crds.yaml
